apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmregler
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosmmottak
    outbound:
      rules:
        - application: syfosmregister
          namespace: teamsykmelding
          cluster: dev-gcp
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvsyfosmregler
        mountPath: /secrets/serviceuser
  webproxy: true
  kafka:
    pool: nav-dev
  ingresses:
    - "https://syfosmregler.nais.preprod.local"
  env:
    - name: HELSENETT_SCOPE
      value: api://dev-fss.teamsykmelding.syfohelsenettproxy/.default
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.nais.preprod.local
    - name: SMREGISTER_URL
      value: https://smregister.dev.nav.no
    - name: SMREGISTER_AUDIENCE
      value: dev-gcp:teamsykmelding:syfosmregister
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.preprod.local/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: SYKETILLFELLE_ENDPOINT_URL
      value: https://flex-syketilfelle.dev.intern.nav.no
    - name: SYKETILLFELLE_SCOPE
      value: api://dev-gcp.flex.flex-syketilfelle/.default