apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmregler
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  vault:
    enabled: true
  webproxy: true
  ingresses:
    - "https://syfosmregler.nais.adeo.no"
  env:
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/token
    - name: CLIENT_ID
      value: 97b74a7f-7cc8-475b-ac1e-6a198824e44c
    - name: HELSENETTPROXY_ID
      value: b813133d-82b8-46ef-be96-3b903ea6c048
