apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: syfosmregler
  namespace: default
  labels:
    team: "teamsykefravr"
spec:
  name: "syfosmregler"
  image: "repo.adeo.no:5443/syfo/syfosmregler:@@VERSION@@"
  replicas:
    min: 1
    max: 10
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /is_ready
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 3300m
      memory: 512Mi
    requests:
      cpu: 700m
      memory: 128Mi
  vault:
    enabled: true
  ingress:
    disabled: false
  env:
  - name: PERSON_V3_ENDPOINT_URL
    value: {{PERSON_V3_ENDPOINT_URL}}
  - name: SECURITY_TOKEN_SERVICE_URL
    value: {{SECURITY_TOKEN_SERVICE_URL}}
  - name: HELSEPERSONELL_V1_ENDPOINT_URL
    value: {{HELSEPERSONELL_V1_ENDPOINT_URL}}
