apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "syfosmregler"
  namespace: "default"
  labels:
    team: "teamsykefravr"
spec:
  image: "repo.adeo.no:5443/syfo/syfosmregler:@@VERSION@@"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /is_ready
    initialDelay: 5
    timeout: 1
    periodSeconds: 10
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 2000m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
  ingress:
    disabled: false
  env:
    - name: CONFIG_FILE
      value: "config-prod.json"
