apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmregler
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 10
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 712Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosmmottak
          namespace: teamsykmelding
          cluster: prod-gcp
    outbound:
      rules:
        - application: syfosmregister
          namespace: teamsykmelding
          cluster: prod-gcp
        - application: flex-syketilfelle
          namespace: flex
          cluster: prod-gcp
        - application: syfohelsenettproxy
        - application: btsys-api
          namespace: team-rocket
          cluster: prod-gcp
      external:
        - host: pdl-api.prod-fss-pub.nais.io
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  env:
    - name: HELSENETT_SCOPE
      value: api://prod-gcp.teamsykmelding.syfohelsenettproxy/.default
    - name: SMREGISTER_AUDIENCE
      value: api://prod-gcp.teamsykmelding.syfosmregister/.default
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: SYKETILLFELLE_SCOPE
      value: api://prod-gcp.flex.flex-syketilfelle/.default
    - name: LEGE_SUSPENSJON_PROXY_SCOPE
      value: api://prod-gcp.team-rocket.btsys-api/.default
    - name: SOURCE_VERSION_URL
      value: {{ sourceVersionURL }}
