apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmregler
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvsyfosmregler
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/syfosmregler/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  ingresses:
    - "https://syfosmregler.nais.preprod.local"
  env:
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: CLIENT_ID
      value: b0f159e9-71af-4a30-8c2b-a02f67b7905a
    - name: HELSENETTPROXY_ID
      value: c18eba24-f676-47db-9a97-3c66e9304aee
