apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmregler
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosmmottak
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvsyfosmregler
        mountPath: /secrets/serviceuser
  webproxy: true
  kafka:
    pool: nav-prod
  ingresses:
    - "https://syfosmregler.nais.adeo.no"
  env:
    - name: HELSENETT_SCOPE
      value: api://prod-fss.teamsykmelding.syfohelsenettproxy/.default
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.nais.adeo.no
    - name: SMREGISTER_SCOPE
      value: "api://prod-fss.teamsykmelding.syfosmregister/.default"
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.adeo.no/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: SYKETILLFELLE_ENDPOINT_URL
      value: https://flex-syketilfelle.intern.nav.no
    - name: SYKETILLFELLE_SCOPE
      value: api://prod-gcp.flex.flex-syketilfelle/.default