apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmregler
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: syfosmmottak
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: teamsykmelding-mock
        - application: testnav-sykemelding-proxy
          namespace: dolly
          cluster: dev-gcp
        - application: testnav-sykemelding-proxy-trygdeetaten
          namespace: dolly
          cluster: dev-gcp
        - application: syk-inn-api
          namespace: tsm
          cluster: dev-gcp
    outbound:
      rules:
        - application: syfosmregister
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: flex-syketilfelle
          namespace: flex
          cluster: dev-gcp
        - application: syfohelsenettproxy
        - application: btsys-api
          namespace: team-rocket
          cluster: dev-gcp
      external:
        - host: pdl-api.dev-fss-pub.nais.io
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  ingresses:
    - "https://syfosmregler.intern.dev.nav.no"
  env:
    - name: HELSENETT_SCOPE
      value: api://dev-gcp.teamsykmelding.syfohelsenettproxy/.default
    - name: SMREGISTER_AUDIENCE
      value: api://dev-gcp.teamsykmelding.syfosmregister/.default
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: SYKETILLFELLE_SCOPE
      value: api://dev-gcp.flex.flex-syketilfelle/.default
    - name: LEGE_SUSPENSJON_PROXY_SCOPE
      value: api://dev-gcp.team-rocket.btsys-api/.default
    - name: SOURCE_VERSION_URL
      value: {{ sourceVersionURL }}
